##############################################################################
# A basic deployment where nginx is run via valgrind, to test for memory leaks
##############################################################################

version: '3.8'
services:

  nginx:
    image: nginx_valgrind:v1
    ports:
    - 8081:8081
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ../../build/alpine.ngx_curity_http_oauth_proxy_module_1.21.3.so:/usr/lib/nginx/modules/ngx_curity_http_oauth_proxy_module.so
    command: >
      sh -c "/usr/bin/valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=/valgrind-results.txt /usr/sbin/nginx"